# Generated by Django 3.0.8 on 2021-11-23 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companybank',
            old_name='ifsc_no',
            new_name='swift_no',
        ),
        migrations.RenameField(
            model_name='employeebank',
            old_name='ifsc_no',
            new_name='swift_no',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='c_gst',
            new_name='gst',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='s_gst',
        ),
    ]
