# Generated by Django 3.0.8 on 2021-11-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalApp', '0002_auto_20211123_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyaccount',
            name='transaction_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='companyaccount',
            name='transaction_type',
            field=models.CharField(choices=[(1, 'Debit'), (2, 'Credit')], max_length=255),
        ),
    ]
